-- Set <space> as the leader key
-- See `:help mapleader`
--  NOTE: Must happen before plugins are required (otherwise wrong leader will be used)
vim.g.mapleader = ' '
vim.g.maplocalleader = ' '
--require "catpuccin_config"
--require("plugin.telescope_config")
--require("plugin.treesitter_config")
--require "plugin.cmp_config"
--require("plugin.lsp_config")
--require("plugin.which-key")
--require "plugin.option"
--require "plugin.keybind"
--require "toggleterm_config"
--require "surround_config"
--require "colorscheme_config"
--require "startup_nvim_config"
--require "lazygit_config"
--require "status_line_config"
--require "barbecue_config"
--require "neoscroll_config"
--require "cursorline_config"
--require "noice_config"
--require "bufferline_config"
--require "mini_config"
--require "trouble_config"
--require "codeium_config"
--require 'after.ftplugin.rust'
